### ISSUE TITLE
.version file pointing at wrong url

### ISSUE THREAD

**Issue by Olympic1** [TriggerAu/KSPTips#5]
KSP-AVC can't check for new versions because the url isn't pointing to a valid .version file. Current link is
https://raw.githubusercontent.com/TriggerAu/ksptips/master/ksptips/ksptips.version

Change it to
https://raw.githubusercontent.com/TriggerAu/KSPTips/master/PluginBuilder/KSPTips.version

**Comment by TriggerAu** [comment]
Forgot to bulid the version file - done now
